name: GitHub Pages

on:
   push:
      branches: [ master ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v2
            with:
               fetch-depth: 0
         -
            name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: ${{ matrix.node-version }}
         -
            shell: bash
            run: |
               pushd scripts/build
               npm ci
               node src/build.js
         -
            uses: peaceiris/actions-gh-pages@v3
            with:
               github_token: ${{ secrets.GITHUB_TOKEN }}
               publish_dir: dist
